apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tidb-builder.fullname" . }}
data:
  pd-Dockerfile: |
    FROM hub.pingcap.net/pingcap/alpine-glibc
    ADD bin/agent /agent
    ADD bin/pd-server /preset_daemon/pd/bin/pd-server
    RUN ln -s /preset_daemon/pd/bin/pd-server /pd-server
    WORKDIR /
    EXPOSE 2379 2380
    ENTRYPOINT ["/pd-server"]

  build-pd.sh: |
    #!/bin/bash
    work_dir=$GOPATH/src/github.com/pingcap/pd
    docker_dir=/root/docker/pd
    repo=https://github.com/{{ template "pd.gitUser" . }}/pd.git
    cd ${work_dir}
    local_branch="{{ template "pd.gitUser" . }}/{{ template "pd.branch" . }}"
    echo "##### Checking out branch {{ template "pd.branch" . }} from ${repo} #####"
    git fetch ${repo} {{ template "pd.branch" . }}:${local_branch}
    git checkout ${local_branch}
    git_rev=$(git rev-parse --short HEAD)
    image="hub.pingcap.net/pingcap/pd:{{ template "pd.gitUser" . }}-${git_rev}"
    echo "##### Making binaries #####"
    make
    cp /bin/agent bin/agent
    cp /scripts/pd-Dockerfile Dockerfile
    echo "##### Building Docker image ${image} #####"
    docker build -t ${image} .
    echo "##### Pushing Docker image ${image} #####"
    docker push ${image}

  tikv-Dockerfile: |
    FROM hub.pingcap.net/pingcap/alpine-glibc
    ADD tikv-bin/agent /agent
    ADD tikv-bin/tikv-server /preset_daemon/tikv/bin/tikv-server
    RUN ln -s /preset_daemon/tikv/bin/tikv-server /tikv-server
    WORKDIR /
    EXPOSE 20160
    ENTRYPOINT ["/tikv-server"]

  build-tikv.sh: |
    #!/bin/bash
    work_dir=/root/tikv
    docker_dir=/root/docker/tikv
    repo=https://github.com/{{ template "tikv.gitUser" . }}/tikv.git
    cd ${work_dir}
    local_branch="{{ template "tikv.gitUser" . }}/{{ template "tikv.branch" . }}"
    echo "##### Checking out branch {{ template "tikv.branch" . }} from ${repo} #####"
    git fetch ${repo} {{ template "tikv.branch" . }}:${local_branch}
    git checkout ${local_branch}
    git_rev=$(git rev-parse --short HEAD)
    image="hub.pingcap.net/pingcap/tikv:{{ template "tikv.gitUser" . }}-${git_rev}"
    rustup override set `tail -n 1 rust-toolchain`
    rustup component add rustfmt-preview --toolchain `tail -n 1 rust-toolchain`
    echo "##### Making binaries #####"
    make dist_release
    mkdir -p tikv-bin
    cp /bin/agent tikv-bin/agent
    cp bin/tikv-server tikv-bin/tikv-server
    cp /scripts/tikv-Dockerfile Dockerfile
    echo "##### Building Docker image ${image} #####"
    docker build -t ${image} .
    echo "##### Pushing Docker image ${image} #####"
    docker push ${image}

  tidb-Dockerfile: |
    FROM hub.pingcap.net/pingcap/alpine-glibc
    ADD bin/agent /agent
    ADD bin/tidb-server /preset_daemon/tidb/bin/tidb-server
    RUN ln -s /preset_daemon/tidb/bin/tidb-server /tidb-server
    WORKDIR /
    EXPOSE 4000 10080
    ENTRYPOINT ["/tidb-server"]

  build-tidb.sh: |
    #!/bin/bash
    work_dir=$GOPATH/src/github.com/pingcap/tidb
    docker_dir=/root/docker/tidb
    repo=https://github.com/{{ template "tidb.gitUser" . }}/tidb.git
    cd ${work_dir}
    local_branch="{{ template "tidb.gitUser" . }}/{{ template "tidb.branch" . }}"
    echo "##### Checking out branch {{ template "tidb.branch" . }} from ${repo} #####"
    git fetch ${repo} {{ template "tidb.branch" . }}:${local_branch}
    git checkout ${local_branch}
    git_rev=$(git rev-parse --short HEAD)
    image="hub.pingcap.net/pingcap/tidb:{{ template "tidb.gitUser" . }}-${git_rev}"
    echo "##### Making binaries #####"
    make
    cp /bin/agent bin/agent
    cp /scripts/tidb-Dockerfile Dockerfile
    echo "##### Building Docker image ${image} #####"
    docker build -t ${image} .
    echo "##### Pushing Docker image ${image} #####"
    docker push ${image}
